service: real-analytics

app: real-analytics
org: dinushankanrg
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    basePath: ./env/

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-south-1
  environment:
    env: ${file(./env/.env.${self:provider.stage})}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "lambda:InvokeFunction"
      Resource:
      - "arn:aws:s3:::${self:app}-${self:provider.stage}/*"
      - "*"
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  data-collector:
    handler: src/modules/data-collector/data.handler
    timeout: 30
    events:
      - http:
          path: '/v1/data-collector/{proxy+}'
          method: any
          cors: true
  data-delivery:
    handler: src/modules/data-delivery/delivery.handler
    timeout: 10
    events:
      - http:
          path: '/v1/data-delivery/{proxy+}'
          method: any
          cors: true
