service: real-analytics

app: real-analytics
org: dinushankanrg
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    basePath: ./env/

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-south-1
  environment:
    env: ${file(./env/.env.${self:provider.stage})}

functions:
  data-collector:
    handler: src/modules/data-collector/data.handler.handler
    events:
      - http:
          path: '/v1/data-collector/{proxy+}'
          method: any
          cors: true
  data-delivery-pipeline:
    handler: src/modules/data-delivery/delivery.handler.handler
    events:
      - http:
          path: '/v1/data-delivery-pipeline/{proxy+}'
          method: any
          cors: true
