service: real-analytics

app: real-analytics
org: dinushankanrg
plugins:
  - serverless-dotenv-plugin
  - serverless-offline-sqs
  - serverless-offline

custom:
  dotenv:
    basePath: ./env/

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-south-1
  environment:
    env: ${file(./env/.env.${self:provider.stage})}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "lambda:InvokeFunction"
        - "sqs:SendMessage"
      Resource:
      - "arn:aws:s3:::${self:app}-${self:provider.stage}/*"
      - "*"
      -  "arn:aws:sqs:${self:provider.region}:*:analyticsSQS"
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  data-collector:
    handler: src/modules/data-collector/data.handler
    timeout: 30
    events:
      - http:
          path: '/v1/data-collector/{proxy+}'
          method: any
          cors: true
  data-delivery:
    handler: src/modules/data-delivery/delivery.handler
    timeout: 10
    events:
      - http:
          path: '/v1/data-delivery/{proxy+}'
          method: any
          cors: true
  data-calculation:
    handler: src/modules/data-calculation/calculation.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - analyticsSQS
              - Arn
          batchSize: 1

resources:
  Resources:
    analyticsSQS:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "analyticsSQS"
